version: "3.2"

services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  dj:
    restart: always
    container_name: dj
    build: code/
    command: python code/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  networks:
    djangonetwork:
      driver: bridge
